### ISSUE TITLE
Slave data

### ISSUE THREAD

**Issue by cfurstenau** [cfurstenau/atakSVG#13]
Slave status colors need to correspond to the correct slave and not just pull from slave A. Also, the values should be updated dynamically.

**Comment by afroebke** [comment]
I've modified the slave svg files and tested them thoroughly on my local laptop vm.  All seems to be working correctly now.  I'm attaching them here for folks' consideration.  If you want me to change them in the main github site or upload them onto the hackathon vm just let me know.  Piece out?



[Updated Slave SVG's.zip](https://github.com/cfurstenau/atakSVG/files/959232/Updated.Slave.SVG.s.zip)

**Comment by LamarcusBrown** [comment]
I love lamp?

*-Marc B.*
